<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
		<LangVersion>latest</LangVersion>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="UI\Assets\arrow-up-down-white.png" />
      <None Remove="UI\Assets\avatar-placeholder.png" />
      <None Remove="UI\Assets\caret_drop_down.png" />
      <None Remove="UI\Assets\circle-user-round.png" />
      <None Remove="UI\Assets\civil3d.png" />
      <None Remove="UI\Assets\clear-icon-white.png" />
      <None Remove="UI\Assets\Clear.png" />
      <None Remove="UI\Assets\clock-icon-white.png" />
      <None Remove="UI\Assets\clock-icon.png" />
      <None Remove="UI\Assets\close-darktheme-default-16px.png" />
      <None Remove="UI\Assets\close-darktheme-disabled-16px.png" />
      <None Remove="UI\Assets\close-darktheme-hover-16px.png" />
      <None Remove="UI\Assets\cloud-upload-white.png" />
      <None Remove="UI\Assets\Date.png" />
      <None Remove="UI\Assets\download-icon-primary.png" />
      <None Remove="UI\Assets\download-icon-white-2.png" />
      <None Remove="UI\Assets\download-icon-white.png" />
      <None Remove="UI\Assets\download-icon.png" />
      <None Remove="UI\Assets\Download.png" />
      <None Remove="UI\Assets\ellipsis-vertical-white.png" />
      <None Remove="UI\Assets\file-up-primary.png" />
      <None Remove="UI\Assets\Filter.png" />
      <None Remove="UI\Assets\folder-open-white.png" />
      <None Remove="UI\Assets\Fonts\Inter-ExtraLight.ttf" />
      <None Remove="UI\Assets\Fonts\Inter-Light.ttf" />
      <None Remove="UI\Assets\Fonts\Inter-Regular.ttf" />
      <None Remove="UI\Assets\Fonts\Inter-SemiBold.ttf" />
      <None Remove="UI\Assets\funnel-icon-white.png" />
      <None Remove="UI\Assets\git-compare-white.png" />
      <None Remove="UI\Assets\logo-dark-2.png" />
      <None Remove="UI\Assets\more-details-white.png" />
      <None Remove="UI\Assets\more-details.png" />
      <None Remove="UI\Assets\Profile.png" />
      <None Remove="UI\Assets\revit.png" />
      <None Remove="UI\Assets\search-icon-white.png" />
      <None Remove="UI\Assets\search_icon_20px.png" />
      <None Remove="UI\Assets\Sort.png" />
      <None Remove="UI\Assets\square-chevron-down-primary.png" />
      <None Remove="UI\Assets\thumbs-up-white.png" />
      <None Remove="UI\Assets\thumbs-up.png" />
      <None Remove="UI\Assets\triangle-alert-red.png" />
      <None Remove="UI\Assets\user-icon-white.png" />
      <None Remove="UI\Assets\user-round-white.png" />
      <None Remove="UI\Assets\workflow-white.png" />
      <None Remove="UI\Assets\workflow.png" />
    </ItemGroup>

	<ItemGroup>
		<Reference Include="DynamoCore">
			<HintPath>C:\Program Files\Autodesk\Revit 2025\AddIns\DynamoForRevit\DynamoCore.dll</HintPath>
			<Private>false</Private>
		</Reference>

		<Reference Include="DynamoCoreWpf">
			<HintPath>C:\Program Files\Autodesk\Revit 2025\AddIns\DynamoForRevit\DynamoCoreWpf.dll</HintPath>
			<Private>false</Private>
		</Reference>

		<Reference Include="DynamoServices">
			<HintPath>C:\Program Files\Autodesk\Revit 2025\AddIns\DynamoForRevit\DynamoServices.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="UI\Assets\arrow-up-down-white.png" />
	  <Resource Include="UI\Assets\avatar-placeholder.png" />
	  <Resource Include="UI\Assets\caret_drop_down.png" />
	  <Resource Include="UI\Assets\circle-user-round.png" />
	  <Resource Include="UI\Assets\civil3d.png" />
	  <Resource Include="UI\Assets\clear-icon-white.png" />
	  <Resource Include="UI\Assets\Clear.png" />
	  <Resource Include="UI\Assets\clock-icon-white.png" />
	  <Resource Include="UI\Assets\clock-icon.png" />
	  <Resource Include="UI\Assets\close-darktheme-default-16px.png" />
	  <Resource Include="UI\Assets\close-darktheme-disabled-16px.png" />
	  <Resource Include="UI\Assets\close-darktheme-hover-16px.png" />
	  <Resource Include="UI\Assets\cloud-upload-white.png" />
	  <Resource Include="UI\Assets\Date.png" />
	  <Resource Include="UI\Assets\download-icon-primary.png" />
	  <Resource Include="UI\Assets\download-icon-white-2.png" />
	  <Resource Include="UI\Assets\download-icon-white.png" />
	  <Resource Include="UI\Assets\download-icon.png" />
	  <Resource Include="UI\Assets\Download.png" />
	  <Resource Include="UI\Assets\ellipsis-vertical-white.png" />
	  <Resource Include="UI\Assets\file-up-primary.png" />
	  <Resource Include="UI\Assets\Filter.png" />
	  <Resource Include="UI\Assets\folder-open-white.png" />
	  <Resource Include="UI\Assets\Fonts\Inter-ExtraLight.ttf" />
	  <Resource Include="UI\Assets\Fonts\Inter-Light.ttf" />
	  <Resource Include="UI\Assets\Fonts\Inter-Regular.ttf" />
	  <Resource Include="UI\Assets\Fonts\Inter-SemiBold.ttf" />
	  <Resource Include="UI\Assets\Fonts\SegoeFluentIcons.ttf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="UI\Assets\funnel-icon-white.png" />
	  <Resource Include="UI\Assets\git-compare-white.png" />
	  <Resource Include="UI\Assets\logo-dark-2.png" />
	  <Resource Include="UI\Assets\more-details-white.png" />
	  <Resource Include="UI\Assets\more-details.png" />
	  <Resource Include="UI\Assets\Profile.png" />
	  <Resource Include="UI\Assets\Requirements-disabled.png" />
	  <Resource Include="UI\Assets\revit.png" />
	  <Resource Include="UI\Assets\search-icon-white.png" />
	  <Resource Include="UI\Assets\search_icon_20px.png" />
	  <Resource Include="UI\Assets\Sort.png" />
	  <Resource Include="UI\Assets\square-chevron-down-primary.png" />
	  <Resource Include="UI\Assets\thumbs-up-white.png" />
	  <Resource Include="UI\Assets\thumbs-up.png" />
	  <Resource Include="UI\Assets\triangle-alert-red.png" />
	  <Resource Include="UI\Assets\user-icon-white.png" />
	  <Resource Include="UI\Assets\user-round-white.png" />
	  <Resource Include="UI\Assets\workflow-white.png" />
	  <Resource Include="UI\Assets\workflow.png" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\Api\Interfaces\" />
	  <Folder Include="Services\Infrastructure\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Clerk.BackendAPI" Version="0.15.1" />
	  <PackageReference Include="DotNetProjects.Extended.Wpf.Toolkit" Version="5.0.129" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.20" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.20">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3800.47" />	  
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BIMformative.Dynamo.Core\BIMformative.Core.csproj" />
	</ItemGroup>
	

	<ItemGroup>
	  <Page Update="UI\Styles\DataGrid.xaml">
	    <CopyToOutputDirectory></CopyToOutputDirectory>
	  </Page>
	  <Page Update="UI\Styles\Image.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

</Project>
