// <auto-generated />
using System;
using BIMformative.DynamoExtension.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIMformative.DynamoExtension.Migrations
{
    [DbContext(typeof(BimformativeDbContext))]
    partial class BimformativeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("BIMformative.DynamoExtension.Models.Scripts.DownloadedScript", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentLocalHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadedHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLocalFileWriteTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadedScripts");
                });
#pragma warning restore 612, 618
        }
    }
}
