<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>

		<AssemblyName>BIMformative.Installer</AssemblyName>
		<RootNamespace>BIMformative.Installer</RootNamespace>

		<Configurations>Debug;Release</Configurations>
  </PropertyGroup>

	<ItemGroup>
		<Folder Include="Build\" />
		<Folder Include="Assets\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="WixSharp.Core" Version="2.13.0" />
	</ItemGroup>

</Project>
